name: crypto_wallet
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  carousel_slider: ^4.1.1
  cryptography: ^2.0.5
  dio: ^4.0.6
  encrypt: ^5.0.1
  ethereum_addresses: ^1.0.2
  firebase_analytics: ^9.1.12
  firebase_core: ^1.19.1
  firebase_messaging: ^12.0.0
  flutter:
    sdk: flutter
  flutter_bitcoin: ^1.0.1
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^9.7.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.9
  flutter_secure_storage: ^5.0.2
  fluttertoast: ^8.0.9
  get_it: ^7.2.0
  hex: ^0.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.4
  intl: ^0.17.0
  modal_bottom_sheet: ^2.1.0
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  web3dart: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.2.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/contracts/erc20/
    - .env.development
    - .env.production

  fonts:
    - family: NanumSquareRound
      fonts:
        - asset: assets/fonts/NanumSquareRoundL.ttf
          weight: 100
        - asset: assets/fonts/NanumSquareRoundR.ttf
          weight: 400
        - asset: assets/fonts/NanumSquareRoundB.ttf
          weight: 700
        - asset: assets/fonts/NanumSquareRoundEB.ttf
          weight: 900

flutter_intl:
  enabled: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/flutter_logo.png
  fullscreen: true

android_12:
  color: "#FFFFFF"
  image: assets/images/flutter_logo.png
  fullscreen: true

ios: false
